### ISSUE TITLE
Handling typography

### ISSUE THREAD

**Issue by felguerez** [airbnb/css#5]
What's the airbnb approach to styling typography? Is it advisable to select type-specific elements (p, header elements) and set their `font-size`, `line-height` and `font-weight` versus labeling each element with classes such as "normal-body", "small-body" ? should these classes be considered utility classes and be used in exceptional cases?

**Comment by mikefowler** [comment]
Howdy @felguerez! The frontend framework that we use internally does a mix of both. For very common typographic elements like `p` and `h1–6` tags we apply styles directly with an element selector. For certain of these we define a utility class to match. For example:

```scss
h1, 
.h1 {
  // font-size, line-height, etc
}
```

For styles that can plausibly be applied to _any_ element, we stick with a utility class, like this:

```scss
.text-lead {
  font-size: 16px;
}
```

There's no right answer here, but a general rule of thumb might be: implement utility classes for the exceptions, and otherwise leverage global styles for commonly reused elements. If your design is consistent this should be fairly easy. It doesn't make sense, for example, to add `.text-body` to every `p` tag if 95% of them use that class.

Does that answer your question?

**Comment by felguerez** [comment]
It does indeed. Thanks Mike. Your rule of thumb is generally the direction we're taking at my org. I appreciate your feedback!

**Comment by mikefowler** [comment]
You're quite welcome!
